server:
  port: 8501

spring:
  application:
    name: cyyaw-service-admin
  jpa: #数据库配置
    hibernate:
      ddl-auto: update
    show-sql: true
    # database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false

  datasource:
    url: jdbc:h2:mem:test_db
    username: root
    password: 123456
    driver-class-name: org.h2.Driver
    schema: classpath:db/schema.sql
    data: classpath:db/data.sql
  h2:
    console:
      enabled: true
