spring:
  application:
    name: spring-zuul

server:
  port: 8769

zuul:
  routes:
    backend-admin:
      path: /admin/**
      serviceId: cyyaw-web-admin
    backend-posts:
      path: /backend/posts/**
      serviceId: itoken-web-posts